export type Locale = "ja" | "en";

export const hubCopy = {
  ja: {
    title: "地球に眠る過去への入り口",
    globe: "地球儀。回すとゲートが見つかる",
    hint: "地球を回して、入口の気配を探そう",
    gateTrace: "かすかな入口の気配",
    ways: (n: number) => `${n}の入り口`,
    sites: "地点",
    records: "記録",
    named: "種",
    ages: "この場所の時代",
    alsoThen: "同じ時代の別の世界",
    enter: "この世界に入る",
    leave: "現代へ戻る",
    close: "閉じる",
    otherAges: "他時代へのゲート",
    maybeMore: "この地球には、ほかにも入口があるかもしれない",
    peek: "のぞいてみる",
    pickAge: "どの時代へ行きますか？",
    pickAgeLede: "同じ場所に開いている、別の時代のゲートです。",
    cancel: "キャンセル",
    goToAge: "この時代へ",
    encountered: "遭遇した生物",
    encounteredNote: "この絵に描かれている生きものです。すべてこのゲートの記録に実在します。",
    findInScene: "想像図の中で探す",
    residentList: "住人リスト",
    moreRecorded: (n: number) => `このほかにも多くの生物が記録されています（全${n}種）。`,
    zoom: "画像を大きく見る",
    residents: "この世界の住人",
    showList: (n: number) => `記録された${n}種を見る`,
    hideList: "記録を閉じる",
    residentsNote: "どこにいたかは、PBDBに記録された生息環境と生活様式によります。",
    cast: (n: number) => `記録されている${n}種のうち`,
    castNote: "記録の多い順。数は発表された記録の件数で、生きものの数ではありません。",
    here: "いまここ",
    menu: "メニュー",
    findGate: "入口を探す",
    language: "言語",
    on: "オン",
    off: "オフ",
    aboutTitle: "この装置について",
    aboutBody: [
      "Earth Lensというアプリを作って、地球をいろいろな角度から眺めているうちに、今度は太古の地球の姿が見たくなりました。",
      "化石が見つかる場所や、地層に残された記録は、現代から太古へつながる“ゲート”のようにも見えます。",
      "そんなゲートを通って、いろんな時代のいろんな地球を見ることができたら面白い。",
      "このアプリは、そんな思いから生まれました。",
    ] as readonly string[],
    aboutSign: "YOKOBO AI LAB",
    aboutSources: [
      ["化石の記録", "Paleobiology Database (CC0)"],
      ["古地形・古座標", "Scotese & Wright (2018) PALEOMAP PaleoDEM (CC BY 4.0)"],
      ["復元図", "描き手の解釈です。描かれた生きものは、そのゲートの記録に実在することを確かめてあります。"],
    ] as ReadonlyArray<readonly [string, string]>,
    log: "ログ",
    logLong: "探索ログ",
    logTitle: "探索ログ",
    logLede: "旅の記録を、整理して、ふりかえる。",
    logVisited: (n: number) => `${n}の世界を訪れた`,
    logSort: "並び替え",
    logSortVisited: "訪れた順",
    logSortOldest: "古い順",
    logSortNewest: "新しい順",
    logSortRegion: "現在の地域別",
    logWorlds: (n: number) => `${n}の世界`,
    logEmpty: "まだどこにも行っていません。地球を回して、入り口を見つけよう。",
    logMore: "過去は、まだまだ広い。",
    logRestart: "旅をはじめからやり直す",
    logResetTitle: "本当に旅をはじめからやり直しますか？",
    logResetBody: "これまで訪れた世界の記録と、旅から見つかった実績は、このブラウザから消えます。元には戻せません。",
    logResetCancel: "やめる",
    logResetConfirm: "旅をやり直す",
    achievement: "実績",
    achievementTitle: "実績",
    achievementGroups: {
      journey: "旅のはじまり",
      time: "時代を渡る",
      vertical: "同じところを掘る",
      horizontal: "同じ地球を回る",
      earth: "地球のかたち",
      record: "世界の中身",
    } as Record<string, string>,
    achievementProgress: (found: number, total: number) => `${found} / ${total}`,
    achievementLede: "旅をしているうちに見つけた、地球の見方。",
    achievementFoundSection: "旅から見つかったもの",
    achievementUnknownSection: "まだ名前のないもの",
    achievementUnknown: "まだ知らない地球の見方がある",
    achievementNew: "新しい実績",
    timescale: "年表",
    timescaleOn: "年表を表示",
    timescaleAt: (era: string) => `いま ${era} のあたり`,
    now: "現代",
    downTo: "同じ場所の、別の時代へ",
    sceneTag: "想像図",
    sceneOpen: "大きく見る",
    sceneNote: "同じ地層から記録された生きものを描いています。同時に同じ場所にいた証拠ではありません。姿・色・光は描き手の解釈です。",
    showCast: "記録された種を見る",
    hideCast: "閉じる",
  },
  en: {
    title: "Ways into the Earth's past",
    globe: "Globe. Turn it to find gates",
    hint: "Turn the Earth and look for a trace of a way in",
    gateTrace: "A faint trace of a way in",
    ways: (n: number) => `${n} ways in`,
    sites: "sites",
    records: "records",
    named: "named",
    ages: "Ages at this place",
    alsoThen: "Another world, same age",
    enter: "Enter this world",
    leave: "Back to the present",
    close: "Close",
    otherAges: "Gates to other ages",
    maybeMore: "This Earth may have other ways in",
    peek: "Look inside",
    pickAge: "Which age?",
    pickAgeLede: "Gates open at this same place, in other ages.",
    cancel: "Cancel",
    goToAge: "Go to this age",
    encountered: "What you meet here",
    encounteredNote: "The creatures painted in this scene. Every one is in this gate’s records.",
    findInScene: "Find in the reconstruction",
    residentList: "The residents",
    moreRecorded: (n: number) => `And many more are recorded here — ${n} species in all.`,
    zoom: "See the picture larger",
    residents: "Who lived here",
    showList: (n: number) => `See the ${n} species recorded`,
    hideList: "Close the record",
    residentsNote: "Where each of them lived is as PBDB records it — the describers’ own environment and life habit.",
    cast: (n: number) => `of ${n} species recorded`,
    castNote: "Most recorded first. Counts are published records, not numbers of animals.",
    here: "You are here",
    menu: "Menu",
    findGate: "Find a gate",
    language: "Language",
    on: "On",
    off: "Off",
    aboutTitle: "About Deep Lens",
    aboutBody: [
      "I built an app called Earth Lens, and after looking at the planet from every angle I could, I started wanting to see the Earth as it used to be.",
      "The places fossils turn up, and the record held in the rock, began to look like gates — ways through from now to deep time.",
      "It would be something, I thought, to step through one of those and stand in a different age of a different Earth.",
      "That is where this came from.",
    ] as readonly string[],
    aboutSign: "YOKOBO AI LAB",
    aboutSources: [
      ["The fossil record", "Paleobiology Database (CC0)"],
      ["Ancient terrain and coordinates", "Scotese & Wright (2018) PALEOMAP PaleoDEM (CC BY 4.0)"],
      ["The reconstructions", "An artist's reading. Every animal drawn has been checked against that gate's own records."],
    ] as ReadonlyArray<readonly [string, string]>,
    log: "Log",
    logLong: "Field log",
    logTitle: "Field log",
    logLede: "The places you travelled to, kept here",
    logVisited: (n: number) => `${n} ${n === 1 ? "world" : "worlds"} visited`,
    logSort: "Sort by",
    logSortVisited: "Visit order",
    logSortOldest: "Oldest first",
    logSortNewest: "Newest first",
    logSortRegion: "Present-day region",
    logWorlds: (n: number) => `${n} ${n === 1 ? "world" : "worlds"}`,
    logEmpty: "Nowhere yet. Turn the Earth and find a way in.",
    logMore: "The past is still wide.",
    logRestart: "Begin the journey again",
    logResetTitle: "Really begin the journey again?",
    logResetBody: "The journey and the discoveries it revealed will be removed from this browser. This cannot be undone.",
    logResetCancel: "Keep my journey",
    logResetConfirm: "Begin again",
    achievement: "Discoveries",
    achievementTitle: "Discoveries",
    achievementGroups: {
      journey: "Setting out",
      time: "Through time",
      vertical: "Digging in one region",
      horizontal: "Around one Earth",
      earth: "The shape of the Earth",
      record: "What a world held",
    } as Record<string, string>,
    achievementProgress: (found: number, total: number) => `${found} / ${total}`,
    achievementLede: "Ways of seeing the Earth that emerged along the journey.",
    achievementFoundSection: "Found along the way",
    achievementUnknownSection: "Still unnamed",
    achievementUnknown: "Another way of seeing the Earth is still unknown",
    achievementNew: "A new discovery",
    timescale: "Scale",
    timescaleOn: "Show the time scale",
    timescaleAt: (era: string) => `Somewhere in the ${era}`,
    now: "the present",
    downTo: "The same place, another age",
    sceneTag: "Reconstruction",
    sceneOpen: "See it larger",
    sceneNote: "Drawn from animals recorded in this same rock unit. That is not evidence they shared one moment. Shapes, colours and light are the artist's reading.",
    showCast: "See the recorded species",
    hideCast: "Close",
  },
} as const;
