export type Locale = "ja" | "en";

export const hubCopy = {
  ja: {
    title: "地球に眠る過去への入り口",
    globe: "地球儀。回すとゲートが見つかる",
    hint: "地球を回して、入り口を見つけよう",
    ways: (n: number) => `${n}の入り口`,
    sites: "地点",
    records: "記録",
    named: "種",
    ages: "この場所の時代",
    alsoThen: "同じ時代の別の世界",
    enter: "この世界に入る",
    leave: "現代へ戻る",
    close: "閉じる",
    cast: (n: number) => `記録されている${n}種のうち`,
    castNote: "記録の多い順。数は発表された記録の件数で、生きものの数ではありません。",
    here: "いまここ",
    log: "ログ",
    logTitle: "探検ログ",
    logLede: "時を旅した、あの景色を、ここに",
    logVisited: "これまでに訪れた場所",
    logEmpty: "まだどこにも行っていません。地球を回して、入り口を見つけよう。",
    logMore: "過去は、まだまだ広い。",
    timescale: "年表",
    timescaleOn: "年表を表示",
    timescaleAt: (era: string) => `いま ${era} のあたり`,
    now: "現代",
    downTo: "同じ場所の、別の時代へ",
    sceneTag: "想像図",
    sceneOpen: "大きく見る",
    sceneNote: "同じ地層から記録された生きものを描いています。同時に同じ場所にいた証拠ではありません。姿・色・光は描き手の解釈です。",
    showCast: "顔ぶれを見る",
    hideCast: "地球を見る",
  },
  en: {
    title: "Ways into the Earth's past",
    globe: "Globe. Turn it to find gates",
    hint: "Turn the Earth and find a way in",
    ways: (n: number) => `${n} ways in`,
    sites: "sites",
    records: "records",
    named: "named",
    ages: "Ages at this place",
    alsoThen: "Another world, same age",
    enter: "Enter this world",
    leave: "Back to the present",
    close: "Close",
    cast: (n: number) => `of ${n} species recorded`,
    castNote: "Most recorded first. Counts are published records, not numbers of animals.",
    here: "You are here",
    log: "Log",
    logTitle: "Field log",
    logLede: "The places you travelled to, kept here",
    logVisited: "Places reached so far",
    logEmpty: "Nowhere yet. Turn the Earth and find a way in.",
    logMore: "The past is still wide.",
    timescale: "Scale",
    timescaleOn: "Show the time scale",
    timescaleAt: (era: string) => `Somewhere in the ${era}`,
    now: "the present",
    downTo: "The same place, another age",
    sceneTag: "Reconstruction",
    sceneOpen: "See it larger",
    sceneNote: "Drawn from animals recorded in this same rock unit. That is not evidence they shared one moment. Shapes, colours and light are the artist's reading.",
    showCast: "Show the cast",
    hideCast: "Back to the globe",
  },
} as const;
