import type { AncientLifeRecord } from "../data/ancientLife";
import type { PresentTraceRecord } from "../data/presentTraces";

export type Locale = "ja" | "en";

export const fossilCopy = {
  ja: {
    language: "言語",
    globeLabel: "回転・ズームできる地球儀",
    timeMode: "時代",
    now: "現在",
    then: "過去",
    present: "現代",
    fourAncientRegions: "95 Ma · 4つの地域",
    fourPresentTraces: "現代 · 4つの痕跡",
    exploreLivingEarth: "生きていた地球を探索",
    followFossil: "化石の痕跡をたどる",
    ancientEarth: "古代地球 · 95 Ma",
    ancientQuestionBefore: "ここには何が",
    ancientQuestionEmphasis: "生きていた？",
    ancientIntro: "地球を回してみよう。同じ時代にも、異なる4つの世界がありました。",
    presentEarth: "現代地球",
    presentQuestionBefore: "いま残る",
    presentQuestionEmphasis: "痕跡を探す",
    presentIntro: "化石の痕跡を選ぶか、地球をタップして、その場所に残る証拠を見てみよう。",
    place: "場所",
    time: "時代",
    life: "生命",
    environment: "環境",
    fourRegions: "4つの地域",
    fourTraceRegions: "4つの痕跡地域",
    regionalBiotas: "地域ごとの生物相",
    fossilTraces: "化石の痕跡",
    environmentsAncient: "海・川・陸",
    recordedLayers: "記録された地層",
    worldView: "全球ビュー",
    regionView: "地域ビュー",
    speciesView: "生物ビュー",
    showTraceInfo: "痕跡の情報を見る",
    optionalEvidence: "証拠レイヤー",
    evidenceOn: "証拠レイヤー · 表示中",
    showPbdb: "PBDB地点を表示",
    hidePbdb: "PBDB地点を隠す",
    evidenceHint: "生命を主役のままにする",
    fossilSitesZoom: (count: number) => `${count.toLocaleString("ja-JP")}件の化石地点 · ズームしてください`,
    recordedEnvironment: "記録された環境",
    modernTraceRegion: "現代の化石記録地域",
    backToAncient: "95 Maへ戻る",
    closeInfo: "情報を閉じる",
    showDetails: "詳細を表示",
    hideDetails: "詳細を隠す",
    regionalWorld: "地域の世界",
    ancientLife: "古代の生命",
    fossilDiscovery: "化石記録 · 現代",
    reconstructedPlace: "復元された場所",
    rockRecord: "岩石記録",
    cenomanianWindow: "セノマニアン期 · 約100.5–93.9 Ma",
    nowDiscovery: "現在 · 化石の場所",
    thenRegion: "95 Ma · 復元された地域",
    dataSource: "データ出典",
    recordedEnvironmentPanel: "記録された環境",
    occurrenceSummary: (count: number) => `この選択に含まれるPBDB記録 ${count.toLocaleString("ja-JP")}件 · 生物の個体数ではありません`,
    seeFossilsToday: "現代の化石を見る",
    driftDistance: "動いた距離",
    livedHere: "ここにいた生きもの",
    backToRegion: "この世界へ戻る",
    backToLiving: "生きていた世界へ戻る",
    pbdbSummary: "PBDB記録の要約",
    sitesAndOccurrences: (sites: number, occurrences: number) => `${sites.toLocaleString("ja-JP")}地点 · ${occurrences.toLocaleString("ja-JP")}件の記録`,
    recordCountNote: "記録数はこのPoCの抽出結果であり、古代の生物数を表すものではありません。",
    presentCallout: "現代では、岩石が見つかる場所に静かな痕跡を示します。95 Maへ戻ると、復元地球上の生きていた地域へ移動します。",
    tracking: "選択を追跡",
    livingWorlds: "95 Ma · 生きていた世界",
    presentFossilTraces: "現代 · 化石の痕跡",
    selectedPlace: "選択した場所",
    closePlace: "場所の情報を閉じる",
    keepGlobeVisible: "地球を見たまま、必要なときだけこの場所の化石記録を開けます。",
    traces: "痕跡",
    readingEvidence: "周辺の証拠を読み込み中…",
    openStrata: (count: number) => `地層の証拠を見る · ${count}`,
    noNearbyStrata: "周辺に地層記録なし",
    strataThroughTime: "この場所を、時間で見る",
    readingRecord: "記録を読み込み中…",
    formationsNearby: (count: number, radius: number) => `${radius} km以内に、化石記録のある地層が${count}件あります`,
    noFormation: (radius: number) => `${radius} km以内では、後期ジュラ紀〜白亜紀の化石を含む地層がPBDBに記録されていません。これは記録の空白であり、生物がいなかったという意味ではありません。`,
    records: "記録",
    thenShort: "当時",
    group: "層群",
    noRecordFor: (millions: number) => `約${millions}百万年間、この場所の記録なし`,
    evidenceOnly: "証拠のみ · AIによる解釈なし。各帯は、発掘・公開された地層を示します。記録数は生物数ではなく、調査量にも左右されます。環境は化石記録に付随する値、位置は各地層の記録地点の中心です。",
  },
  en: {
    language: "LANGUAGE",
    globeLabel: "Interactive Earth globe",
    timeMode: "TIME MODE",
    now: "NOW",
    then: "THEN",
    present: "Present",
    fourAncientRegions: "95 MA · FOUR REGIONS",
    fourPresentTraces: "PRESENT · FOUR TRACES",
    exploreLivingEarth: "EXPLORE THE LIVING EARTH",
    followFossil: "FOLLOW THE FOSSIL",
    ancientEarth: "ANCIENT EARTH · 95 MA",
    ancientQuestionBefore: "Who lived here —",
    ancientQuestionEmphasis: "then?",
    ancientIntro: "Turn the globe. One time window, four very different worlds.",
    presentEarth: "PRESENT EARTH",
    presentQuestionBefore: "Find what remains —",
    presentQuestionEmphasis: "now",
    presentIntro: "Choose a fossil trace, or tap the Earth to inspect the evidence beneath a place.",
    place: "PLACE",
    time: "TIME",
    life: "LIFE",
    environment: "ENVIRONMENT",
    fourRegions: "4 regions",
    fourTraceRegions: "4 trace regions",
    regionalBiotas: "Regional biotas",
    fossilTraces: "Fossil traces",
    environmentsAncient: "Sea · rivers · land",
    recordedLayers: "Recorded layers",
    worldView: "WORLD VIEW",
    regionView: "REGION VIEW",
    speciesView: "SPECIES VIEW",
    showTraceInfo: "SHOW INFO · FOSSIL TRACES",
    optionalEvidence: "OPTIONAL EVIDENCE",
    evidenceOn: "EVIDENCE LAYER · ON",
    showPbdb: "SHOW PBDB DOTS",
    hidePbdb: "HIDE PBDB DOTS",
    evidenceHint: "Life stays in the foreground",
    fossilSitesZoom: (count: number) => `${count.toLocaleString("en-US")} fossil sites · zoom in`,
    recordedEnvironment: "RECORDED ENVIRONMENT",
    modernTraceRegion: "Modern fossil-record region",
    backToAncient: "BACK TO 95 MA",
    closeInfo: "Close information",
    showDetails: "Show details",
    hideDetails: "Hide details",
    regionalWorld: "REGIONAL WORLD",
    ancientLife: "ANCIENT LIFE",
    fossilDiscovery: "FOSSIL DISCOVERY · PRESENT",
    reconstructedPlace: "PLACE · RECONSTRUCTED",
    rockRecord: "ROCK RECORD",
    cenomanianWindow: "Cenomanian window · ~100.5–93.9 Ma",
    nowDiscovery: "NOW · DISCOVERY",
    thenRegion: "THEN · RECONSTRUCTED REGION",
    dataSource: "DATA SOURCE",
    recordedEnvironmentPanel: "RECORDED ENVIRONMENT",
    occurrenceSummary: (count: number) => `${count.toLocaleString("en-US")} PBDB occurrence ${count === 1 ? "record" : "records"} in this selection · not an abundance estimate`,
    seeFossilsToday: "SEE FOSSILS TODAY",
    driftDistance: "GROUND MOVED",
    livedHere: "WHO LIVED HERE",
    backToRegion: "BACK TO THIS WORLD",
    backToLiving: "BACK TO THE LIVING WORLD",
    pbdbSummary: "PBDB RECORD SUMMARY",
    sitesAndOccurrences: (sites: number, occurrences: number) => `${sites.toLocaleString("en-US")} sites · ${occurrences.toLocaleString("en-US")} occurrences`,
    recordCountNote: "Counts describe records in this prototype selection, not the abundance of ancient life.",
    presentCallout: "Present shows quiet traces where the rocks are found today. Return to 95 Ma to see the living region on the reconstructed Earth.",
    tracking: "TRACKING SELECTION",
    livingWorlds: "95 MA · LIVING WORLDS",
    presentFossilTraces: "PRESENT · FOSSIL TRACES",
    selectedPlace: "Selected place",
    closePlace: "Close selected place",
    keepGlobeVisible: "Keep the globe in view. Open the fossil record only when you want the evidence beneath this place.",
    traces: "Traces",
    readingEvidence: "READING NEARBY EVIDENCE…",
    openStrata: (count: number) => `OPEN STRATA EVIDENCE · ${count}`,
    noNearbyStrata: "NO NEARBY STRATA RECORD",
    strataThroughTime: "THIS PLACE, THROUGH TIME",
    readingRecord: "Reading the record…",
    formationsNearby: (count: number, radius: number) => `${count} formations with recorded fossils within ${radius} km`,
    noFormation: (radius: number) => `No fossil-bearing formation is recorded within ${radius} km of this point, in the Late Jurassic to Cretaceous. That is a gap in the record, not an empty world.`,
    records: "records",
    thenShort: "then",
    group: "Group",
    noRecordFor: (millions: number) => `no record here for about ${millions} Myr`,
    evidenceOnly: "EVIDENCE ONLY · NO AI INTERPRETATION. Each band is a formation that someone dug and published. Records count published occurrences, not animals, and follow collecting effort as much as life. Environments come from the fossil records; positions use each formation's recorded-site centre.",
  },
} as const;

const regionJa: Record<string, string> = {
  "North Africa": "北アフリカ",
  Patagonia: "パタゴニア",
  "Eastern Australia": "オーストラリア東部",
  "North America": "北アメリカ",
};

const ecosystemNameJa: Record<string, string> = {
  "kem-kem-ecosystem": "ケムケムのデルタ地帯",
  "huincul-ecosystem": "ウインクルの氾濫原",
  "winton-ecosystem": "ウィントンの河川森林",
  "greenhorn-ecosystem": "西部内陸海路",
};

const categoryJa: Record<string, string> = {
  "river and delta ecosystem": "河川・デルタの生態系",
  "spinosaurid theropod": "スピノサウルス科の獣脚類",
  "large theropod": "大型獣脚類",
  sauropod: "竜脚類",
  pterosaur: "翼竜",
  "sawfish-like ray": "ノコギリエイに似たエイ類",
  "river and floodplain ecosystem": "河川・氾濫原の生態系",
  "abelisaurid theropod": "アベリサウルス科の獣脚類",
  "river and forest ecosystem": "河川・森林の生態系",
  "megaraptoran theropod": "メガラプトル類の獣脚類",
  "titanosaurian sauropod": "ティタノサウルス類の竜脚類",
  conifer: "針葉樹",
  "open marine ecosystem": "外洋性の海洋生態系",
  "lamniform shark": "ネズミザメ目のサメ",
  "large predatory fish": "大型肉食魚",
  "durophagous shark": "硬い殻を砕くサメ",
  "straight-shelled ammonite": "直線的な殻を持つアンモナイト",
};

const environmentJa: Record<string, string> = {
  "Delta channels · lakes · estuaries": "デルタの水路・湖・河口",
  "Deltaic and river deposits": "デルタ・河川堆積物",
  "Fluvial and lake deposits": "河川・湖成堆積物",
  "Deltaic deposits": "デルタ堆積物",
  "Fluvial deposits": "河川堆積物",
  "Estuary and bay deposits": "河口・湾の堆積物",
  "River channels · floodplains · lakes": "河道・氾濫原・湖",
  "River-channel deposits": "河道堆積物",
  "Floodplain deposits": "氾濫原堆積物",
  "Terrestrial deposits": "陸成堆積物",
  "Fine channel-fill deposits": "細粒の河道充填堆積物",
  "Carbonate shelf · open marine water": "炭酸塩棚・外洋域",
  "Deep subtidal carbonate ramp": "深い潮下帯の炭酸塩ランプ",
  "Basinal carbonate deposits": "海盆の炭酸塩堆積物",
};

const ecosystemDescriptionJa: Record<string, string> = {
  "kem-kem-ecosystem": "河川・湖・デルタ・河口から陸域まで、水によって形づくられた北アフリカの生態系です。",
  "huincul-ecosystem": "海岸ではなく、河川と陸上の記録が中心となる南半球の氾濫原生態系です。",
  "winton-ecosystem": "恐竜と針葉樹がともに記録された、高緯度の河川と森林の世界です。",
  "greenhorn-ecosystem": "陸上恐竜の世界とは異なり、サメ・大型魚・アンモナイト・二枚貝が記録された内海です。",
};

const traceNameJa: Record<string, string> = {
  "kem-kem-trace": "ケムケムの化石記録",
  "huincul-trace": "ウインクルの化石記録",
  "winton-trace": "ウィントンの化石記録",
  "greenhorn-trace": "グリーンホーンの化石記録",
};

const tracePlaceJa: Record<string, string> = {
  Morocco: "モロッコ",
  Argentina: "アルゼンチン",
  Australia: "オーストラリア",
  "United States": "アメリカ合衆国",
};

const traceDescriptionJa: Record<string, string> = {
  "kem-kem-trace": "現在のモロッコ南東部に露出する岩石には、95 Maの地球で示した河川・デルタの世界が保存されています。",
  "huincul-trace": "パタゴニアの露頭には、古代地球で示した南半球の氾濫原生態系の痕跡が残っています。",
  "winton-trace": "クイーンズランド州の露頭には、95 Maの高緯度河川森林の証拠が保存されています。",
  "greenhorn-trace": "現在のアメリカ中部に露出する海成石灰岩は、95 Maの地球にあった内海を記録しています。",
};

export function localizeLife(record: AncientLifeRecord, locale: Locale) {
  if (locale === "en") return record;
  return {
    ...record,
    name: ecosystemNameJa[record.id] ?? record.name,
    regionLabel: regionJa[record.regionLabel] ?? record.regionLabel,
    category: categoryJa[record.category] ?? record.category,
    environment: environmentJa[record.environment] ?? record.environment,
    description: ecosystemDescriptionJa[record.id]
      ?? `${record.name}は、${regionJa[record.regionLabel] ?? record.regionLabel}の${record.formationLabel}から記録された${categoryJa[record.category] ?? record.category}です。`,
    sourceLabel: "古生物学データベース · セノマニアン期の化石記録",
    coordinateNote: "マーカーはPBDBのPALEOMAP（Scotese）古座標に基づきます。生息域の境界を示すものではありません。",
  };
}

export function localizeTrace(record: PresentTraceRecord, locale: Locale) {
  if (locale === "en") return record;
  return {
    ...record,
    name: traceNameJa[record.id] ?? record.name,
    placeLabel: tracePlaceJa[record.placeLabel] ?? record.placeLabel,
    description: traceDescriptionJa[record.id] ?? record.description,
    sourceLabel: `古生物学データベース · ${record.formationLabel}`,
    coordinateNote: "現代マーカーは、ローカルデータ内の該当地層記録を件数で重みづけした中心です。個別の発掘地点を示すピンではありません。",
  };
}

export function environmentLabel(locale: Locale, value: string) {
  if (locale === "en") return value;
  const labels: Record<string, string> = {
    SEA: "海",
    "COAST · DELTA": "海岸・デルタ",
    "RIVER · LAKE": "川・湖",
    "DRY LAND": "陸地",
    "NOT RECORDED": "記録なし",
  };
  return labels[value] ?? value;
}
